spring:
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      uri:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: resource-service

yandex:
  key-id:
  secret:
  bucket-name:
  host:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:

security:
  secret: