spring:
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      uri: ${MONGODB_URI}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:50MB}
      max-request-size: ${MAX_REQUEST_SIZE:50MB}
  application:
    name: resource-service

yandex:
  key-id: ${YANDEX_KEY_ID}
  secret: ${YANDEX_SECRET}
  bucket-name: ${YANDEX_BUCKET_NAME}
  host: ${YANDEX_HOST}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8765/eureka}